[workspace]
members = ["flows"]
resolver = "2"

[workspace.dependencies]
async-io = "2.2"
either = "1.9.0"
futures-util = { version = "0.3", features = ["sink"] }
futures = "0.3"
pin-project-lite = "0.2"
